name: mobile_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # මම මෙය standard version එකට වෙනස් කළා, ගැටළු අඩු වෙන්න.

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Networking & Auth
  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1         # <-- Missing Package Added
  shared_preferences: ^2.2.3  # <-- Missing Package Added

  # UI Components
  dropdown_search: ^6.0.2
  percent_indicator: ^4.2.5
     # <-- Missing Package Added (Translation)

  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  easy_localization: ^3.0.8
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  intl: 0.20.2
  payhere_mobilesdk_flutter: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.3.1"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/icons/app_icon/
    - assets/translations/
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon/app_logo.png"
  min_sdk_android: 21 

flutter_native_splash:
  color: "#FFFFFF" 
  image: "assets/icons/app_icon/app_logo.png"
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  android_12:
    color: "#FFFFFF"
    image: "assets/icons/app_icon/app_logo_circle.png"