name: Auto Merge PR

on:
  
  workflow_run:
    workflows: ["Flutter CI", "Backend CI (Node.js)"] 
    types:
      - completed

jobs:
  merge-pr:
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge PR automatically
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         
          gh pr merge --auto --merge "${{ github.event.workflow_run.head_branch }}"